algoritmo "Contagem"

// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : [Gustavo Guanabara]
// Descrição   : AULA 009: Estruturas de repetição
// Autor(a)    : Alexandre Malta Muniz
// Data atual  : 22/09/2023

var

// Declaração de variáveis

    c, f: inteiro

inicio

// Estrutura de repetição

    c <- 0
    f <- 10

    enquanto (c < f) faca
        escreva(c <- c + 1)
    fimenquanto

fimalgoritmo